cải tiến bảo mật check thư viện wp cli

diff --git a/tool-wptangtoc-ols/wptangtoc b/tool-wptangtoc-ols/wptangtoc
--- a/tool-wptangtoc-ols/wptangtoc
+++ b/tool-wptangtoc-ols/wptangtoc
@@ -11,41 +11,33 @@ export LC_ALL=en_US.UTF-8 2>/dev/null
 # 1. KIỂM TRA PHỤ THUỘC LÕI (DEPENDENCIES)
 # ==============================================================================
 function check_dependencies() {
-  local missing_tools=()
-  local os_packages=()
-  local tools=("pv" "wp" "curl" "zip" "unzip" "wget")
+	local missing_tools=()
+	local os_packages=()
+	local tools=("pv" "curl" "zip" "unzip" "wget")
 
-  for tool in "${tools[@]}"; do
-    if [[ "$tool" == "wp" ]]; then
-      if ! command -v wp &>/dev/null && [ ! -f /usr/local/bin/wp ] && [ ! -f /usr/bin/wp ]; then
-        missing_tools+=("wp")
-      fi
-    else
-      if ! command -v "$tool" &>/dev/null; then
-        missing_tools+=("$tool")
-        os_packages+=("$tool")
-      fi
-    fi
-  done
+	for tool in "${tools[@]}"; do
+		if [[ "$tool" == "wp" ]]; then
+			if ! command -v wp &>/dev/null && [ ! -f /usr/local/bin/wp ] && [ ! -f /usr/bin/wp ]; then
+				missing_tools+=("wp")
+			fi
+		else
+			if ! command -v "$tool" &>/dev/null; then
+				missing_tools+=("$tool")
+				os_packages+=("$tool")
+			fi
+		fi
+	done
 
-  if [ ${#missing_tools[@]} -ne 0 ]; then
-    echo -e "\033[1;33mĐang tự động cài đặt các công cụ còn thiếu: ${missing_tools[*]}...\033[0m"
-    if [ -f /etc/redhat-release ]; then
-      dnf install -y epel-release >/dev/null 2>&1
-      dnf install -y "${os_packages[@]}" >/dev/null 2>&1
-    elif [ -f /etc/debian_version ]; then
-      apt-get update >/dev/null 2>&1
-      apt-get install -y "${os_packages[@]}" >/dev/null 2>&1
-    fi
-
-    if [[ " ${missing_tools[*]} " =~ " wp " ]]; then
-      curl -sO https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
-      chmod +x wp-cli.phar
-      mv wp-cli.phar /usr/local/bin/wp
-      ln -sf /usr/local/bin/wp /usr/bin/wp
-    fi
-    # clear
-  fi
+	if [ ${#missing_tools[@]} -ne 0 ]; then
+		echo -e "\033[1;33mĐang tự động cài đặt các công cụ còn thiếu: ${missing_tools[*]}...\033[0m"
+		if [ -f /etc/redhat-release ]; then
+			dnf install -y epel-release >/dev/null 2>&1
+			dnf install -y "${os_packages[@]}" >/dev/null 2>&1
+		elif [ -f /etc/debian_version ]; then
+			apt-get update >/dev/null 2>&1
+			apt-get install -y "${os_packages[@]}" >/dev/null 2>&1
+		fi
+	fi
 }
 check_dependencies
 
