cải tiến luồng dữ liệu tiết kiệm ram máy chủ hơn

diff --git a/tool-wptangtoc-ols/bao-mat/csf/wptt-huy-cai-dat-csf b/tool-wptangtoc-ols/bao-mat/csf/wptt-huy-cai-dat-csf
--- a/tool-wptangtoc-ols/bao-mat/csf/wptt-huy-cai-dat-csf
+++ b/tool-wptangtoc-ols/bao-mat/csf/wptt-huy-cai-dat-csf
@@ -1,88 +1,81 @@
 #!/bin/bash
 
-function huong_dan(){
-Tính năng Hủy cài đặt CSF [Uninstall CSF] trong WPTangToc OLS cho phép bạn gỡ bỏ hoàn toàn ConfigServer Security & Firewall [CSF] và các thành phần liên quan [như Login Failure Daemon - LFD] ra khỏi máy chủ của mình.
+function huong_dan() {
+  Tính năng Hủy cài đặt CSF [Uninstall CSF] trong WPTangToc OLS cho phép bạn gỡ bỏ hoàn toàn ConfigServer Security &
+  Firewall [CSF] và các thành phần liên quan [như Login Failure Daemon - LFD] ra khỏi máy chủ của mình.
 
-🎯 Mục đích của việc hủy cài đặt CSF
-Người dùng có thể muốn gỡ bỏ CSF vì một số lý do:
- * Khắc phục sự cố: Nếu CSF bị nghi ngờ gây ra xung đột với các dịch vụ khác hoặc chặn nhầm các truy cập hợp lệ mà khó cấu hình lại.
- * Chuyển đổi giải pháp tường lửa: Quyết định sử dụng một phần mềm tường lửa khác thay thế cho CSF.
- * Đơn giản hóa hệ thống: Nếu không còn nhu cầu sử dụng các tính năng nâng cao của CSF hoặc cảm thấy nó quá phức tạp để quản lý.
- * Dọn dẹp trước khi cài đặt lại: Muốn gỡ bỏ hoàn toàn phiên bản hiện tại để thực hiện cài đặt mới CSF.
+  🎯 Mục đích của việc hủy cài đặt CSF
+  Người dùng có thể muốn gỡ bỏ CSF vì một số lý do:
+  * Khắc phục sự cố: Nếu CSF bị nghi ngờ gây ra xung đột với các dịch vụ khác hoặc chặn nhầm các truy cập hợp lệ mà khó cấu hình lại.
+  * Chuyển đổi giải pháp tường lửa: Quyết định sử dụng một phần mềm tường lửa khác thay thế cho CSF.
+  * Đơn giản hóa hệ thống: Nếu không còn nhu cầu sử dụng các tính năng nâng cao của CSF hoặc cảm thấy nó quá phức tạp để quản lý.
+  * Dọn dẹp trước khi cài đặt lại: Muốn gỡ bỏ hoàn toàn phiên bản hiện tại để thực hiện cài đặt mới CSF.
 
-Tóm lại, tính năng hủy cài đặt CSF trong WPTangToc OLS giúp bạn gỡ bỏ CSF một cách tương đối dễ dàng và sạch sẽ. Tuy nhiên, đây là một hành động cần cân nhắc kỹ lưỡng về mặt an ninh.
+  Tóm lại, tính năng hủy cài đặt CSF trong WPTangToc OLS giúp bạn gỡ bỏ CSF một cách tương đối dễ dàng và sạch sẽ. Tuy nhiên, đây là một hành động cần cân nhắc kỹ lưỡng về mặt an ninh.
 }
-
 
 echo "========================================================================="
 echo "|Quản lý bảo mật => CSF => Hủy Cài Đặt                                  |"
 echo "========================================================================="
 
-if [[ -f /etc/csf/csf.conf ]];then
+if [[ -f /etc/csf/csf.conf ]]; then
 
-echo "Huỷ cài đặt CSF : $(date '+%d-%m-%Y %H:%M')" >> /var/log/wptangtoc-ols.log
-systemctl stop csf
-systemctl stop lfd
-systemctl disable csf
-systemctl stop lfd
-. /etc/csf/uninstall.sh
-yum install remove perl-libwww-perl.noarch perl-Time-HiRes -y
-rm -rf /etc/csf
-systemctl unmask firewalld
-systemctl start firewalld
-systemctl enable firewalld
-firewall-cmd --zone=public --add-service=http --add-service=https --permanent
-firewall-cmd --zone=public --add-port=443/udp --permanent
-port_ssh=$(cat /etc/ssh/sshd_config | grep "Port " | grep -o '[0-9]\+$'|| echo 22)
+  echo "Huỷ cài đặt CSF : $(date '+%d-%m-%Y %H:%M')" >>/var/log/wptangtoc-ols.log
+  systemctl stop csf
+  systemctl stop lfd
+  systemctl disable csf
+  systemctl stop lfd
+  . /etc/csf/uninstall.sh
+  yum install remove perl-libwww-perl.noarch perl-Time-HiRes -y
+  rm -rf /etc/csf
+  systemctl unmask firewalld
+  systemctl start firewalld
+  systemctl enable firewalld
+  firewall-cmd --zone=public --add-service=http --add-service=https --permanent
+  firewall-cmd --zone=public --add-port=443/udp --permanent
+  port_ssh=$(cat /etc/ssh/sshd_config | grep "Port " | grep -o '[0-9]\+$' || echo 22)
 
-firewall-cmd --zone=public --add-port=${port_ssh}/tcp --permanent
+  firewall-cmd --zone=public --add-port=${port_ssh}/tcp --permanent
 
-path_webgui="/usr/local/lsws/conf/disablewebconsole"
-if [[ ! -f $path_webgui ]]; then
-port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | grep -o '[0-9]\+$')
-firewall-cmd --zone=public --add-port=${port_webgui_openlitespeed}/tcp --permanent
-fi
+  path_webgui="/usr/local/lsws/conf/disablewebconsole"
+  if [[ ! -f $path_webgui ]]; then
+    port_webgui_openlitespeed=$(cat /usr/local/lsws/admin/conf/admin_config.conf | grep "address" | grep -o '[0-9]\+$')
+    firewall-cmd --zone=public --add-port=${port_webgui_openlitespeed}/tcp --permanent
+  fi
 
+  #remote mariadb
+  if $(cat /etc/*release | grep -q "Ubuntu"); then
+    duong_dan_cau_hinh_mariadb="/etc/mysql/my.cnf"
+  else
+    duong_dan_cau_hinh_mariadb="/etc/my.cnf.d/server.cnf"
+  fi
 
+  port_mariadb_remote=$(cat $duong_dan_cau_hinh_mariadb | grep 'port=' | grep -o '[0-9]\+$')
+  if [[ $port_mariadb_remote ]]; then
+    firewall-cmd --zone=public --add-port=${port_mariadb_remote}/tcp --permanent
+  fi
 
-#remote mariadb
-if $(cat /etc/*release | grep -q "Ubuntu") ; then
-	duong_dan_cau_hinh_mariadb="/etc/mysql/my.cnf"
+  firewall-cmd --reload >/dev/null 2>&1
+
+  #tuong thich csf iptable với fail2ban
+  # sed -i 's/action = iptables-multiport\[name=wordpress, port="http,https", protocol=tcp\]/action = firewallcmd-allports/g' /etc/fail2ban/jail.local
+  # sed -i "s/banaction = iptables-multiport/banaction = firewallcmd-multiport/g" /etc/fail2ban/jail.local
+  # sed -i 's/banaction_allports = iptables-allports/banaction_allports = firewallcmd-allports/g' /etc/fail2ban/jail.local
+
+  sed -i '/%(action_)s/!s/^action = .*/action = firewallcmd-allports/' /etc/fail2ban/jail.local
+  sed -i '/%(banaction_allports)s/!s/^banaction = .*/banaction = firewallcmd-allports/' /etc/fail2ban/jail.local
+  sed -i "s/^banaction_allports = .*/banaction_allports = firewallcmd-allports/" /etc/fail2ban/jail.local
+
+  systemctl restart fail2ban
+
+  fail2ban-client reload >/dev/null 2>&1
+
+  echo "Hoàn tất Xóa cài đặt CSF và đồng thời bật lại firewalld"
 else
-	duong_dan_cau_hinh_mariadb="/etc/my.cnf.d/server.cnf"
-fi
-
-port_mariadb_remote=$(cat $duong_dan_cau_hinh_mariadb | grep 'port='| grep -o '[0-9]\+$')
-if [[ $port_mariadb_remote ]];then
-firewall-cmd --zone=public --add-port=${port_mariadb_remote}/tcp --permanent
-fi
-
-
-firewall-cmd --reload >/dev/null 2>&1
-
-#tuong thich csf iptable với fail2ban
-# sed -i 's/action = iptables-multiport\[name=wordpress, port="http,https", protocol=tcp\]/action = firewallcmd-allports/g' /etc/fail2ban/jail.local
-# sed -i "s/banaction = iptables-multiport/banaction = firewallcmd-multiport/g" /etc/fail2ban/jail.local
-# sed -i 's/banaction_allports = iptables-allports/banaction_allports = firewallcmd-allports/g' /etc/fail2ban/jail.local
-
-
-sed -i '/%(action_)s/!s/^action = .*/action = firewallcmd-allports/'  /etc/fail2ban/jail.local
-sed -i '/%(banaction_allports)s/!s/^banaction = .*/banaction = firewallcmd-allports/'  /etc/fail2ban/jail.local
-sed -i "s/^banaction_allports = .*/banaction_allports = firewallcmd-allports/" /etc/fail2ban/jail.local
-
-
-systemctl restart fail2ban
-
-fail2ban-client reload >/dev/null 2>&1
-
-
-echo "Hoàn tất Xóa cài đặt CSF và đồng thời bật lại firewalld"
-else
-echo "Bạn chưa đã cài đặt CSF"
+  echo "Bạn chưa đã cài đặt CSF"
 fi
 
 check_menu_wptangtoc_active=$1
-if [[ $check_menu_wptangtoc_active = "98" ]];then
-. /etc/wptt/bao-mat/csf-main 1
+if [[ $check_menu_wptangtoc_active = "98" ]]; then
+  exec /etc/wptt/bao-mat/csf-main 1
 fi
-
