cai tien chong ddos

diff --git a/tool-wptangtoc-ols/fail2ban/wptt-mokhoaip b/tool-wptangtoc-ols/fail2ban/wptt-mokhoaip
--- a/tool-wptangtoc-ols/fail2ban/wptt-mokhoaip
+++ b/tool-wptangtoc-ols/fail2ban/wptt-mokhoaip
@@ -3,11 +3,35 @@ echo ""
 echo ""
 echo ""
 echo "========================================================================="
-echo "|Quan ly Fail2ban => Mo khoa IP                                         |"
+echo "|Quản lý Mở/khóa IP => Mở khoá IP                                       |"
 echo "========================================================================="
 
-read -p "Nhap Ip ban muon mo khoa: " ip
-fail2ban-client set sshd unbanip $ip
-echo "Dang tien hanh mo khoa IP $ip ..."
-echo "Da mo khoa IP $ip."
-echo "hoan thanh"
+read -p "Nhập ip bạn muốn mở khoá: " ip
+if ! [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+echoDo "Bạn nhập không đúng định dạng IPv4"
+. /etc/wptt/wptt-khoa-ip-main 1
+exit
+fi
+
+if [[ $ip = '' || $ip = '0' ]];then
+	check_menu_wptangtoc_active=$1
+	if [[ $check_menu_wptangtoc_active = "98" ]];then
+		. /etc/wptt/wptt-bao-mat-main 1
+	fi
+	return 2>/dev/null;exit
+fi
+
+. /etc/wptt/echo-color
+_runing "Mở khoá ip $ip"
+# fail2ban-client set sshd unbanip $ip
+for rules in $(fail2ban-client status | grep 'Jail list:' | cut -f2 -d ':' | tr ',' '\n' | uniq | sed 's/\t//g' |sed 's/ //g');do
+fail2ban-client set $rules unbanip $ip >/dev/null 2>&1
+done
+
+_rundone "Mở khoá ip $ip"
+check_menu_wptangtoc_active=$1
+if [[ $check_menu_wptangtoc_active = "98" ]];then
+. /etc/wptt/wptt-bao-mat-main 1
+fi
+
+
